<?php
defined('ABSPATH') || exit;

function eit_get_books() {
    return [
        ['281', '281-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Arzu Demirel', 'Vicdan Özbay'], 'Kitap Listesi', 'İşlemde', '', false],
        ['431', '431-Matematik-11', 'Matematik', '11. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Cüneyt Akçakaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['362', '362-Biyoloji-10', 'Biyoloji', '10. Sınıf', 'Lise', 'Tutku', '2025-11', ['Ender Ünver', 'Halime Cengiz', 'Zafer Arslan'], 'Kitap Listesi', 'İşlemde', 'Murat Şimşek', false],
        ['428', '428-Biyoloji-11', 'Biyoloji', '11. Sınıf', 'Lise', '', '2026-11', ['Ender Ünver', 'Zafer Arslan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['427', '427-Biyoloji-11', 'Biyoloji', '11. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Salim İlker Filiz'], 'Kitap Listesi', 'İşlemde', '', false],
        ['426', '426-Tarih-10', 'Tarih', '10. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Murat Usta'], 'Kitap Listesi', 'İşlemde', '', false],
        ['425', '425-Matematik-10', 'Matematik', '10. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Salih Yıldız'], 'Kitap Listesi', 'İşlemde', '', false],
        ['424', '424-Peygamberimizin Hayatı-07', 'Peygamberimizin Hayatı', '7. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['423', '423-Fen Bilimleri-07', 'Fen Bilimleri', '7. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Sümeyye Türker', 'Zühre Üçüncü'], 'Kitap Listesi', 'İşlemde', '', false],
        ['354', '354-Kimya-10', 'Kimya', '10. Sınıf', 'Lise', 'Tutku', '2025-11', ['Barış Demirdağ'], 'Kitap Listesi', 'İşlemde', '', false],
        ['78', '78-Matematik-12', 'Matematik', '12. Sınıf', 'Lise', 'Dikey', '2025-11', ['Celalettin Keskin'], 'Kitap Listesi', 'İşlemde', '', false],
        ['300', '300-Kimya-09', 'Kimya', '9. Sınıf', 'Lise', 'Dikey', '2025-11', ['Tuğba Bozkaya', 'Uğur Bozkaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['303', '303-Kimya-09', 'Kimya', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Barış Demirdağ'], 'Kitap Listesi', 'İşlemde', '', false],
        ['62', '62-Fizik-12', 'Fizik', '12. Sınıf', 'Lise', 'Dikey', '2025-11', ['Muhammed Çoruh'], 'Kitap Listesi', 'İşlemde', '', false],
        ['295', '295-Fizik-09', 'Fizik', '9. Sınıf', 'Lise', 'Dikey', '2025-11', ['İlknur ÖZkan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['310', '310-Tarih-09', 'Tarih', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Hakan Işık'], 'Kitap Listesi', 'İşlemde', '', false],
        ['185', '185-Fen Bilimleri-08', 'Fen Bilimleri', '8. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Ayşe Seyrek', 'Sümeyye Türker', 'Tuğba Bozkaya', 'Zühre Üçüncü'], 'Kitap Listesi', 'İşlemde', '', false],
        ['140', '140-İngilizce-08', 'İngilizce', '8. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Esra Kandilci', 'Necla Tuğba Yüksel'], 'Kitap Listesi', 'İşlemde', '', false],
        ['226', '226-İngilizce-08', 'İngilizce', '8. Sınıf', 'Ortaokul', 'Ankakuşu', '2025-11', ['Esra Kandilci'], 'Kitap Listesi', 'İşlemde', '', false],
        ['347', '347-Fen Bilimleri-06', 'Fen Bilimleri', '6. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Sümeyye Türker', 'Zühre Üçüncü'], 'Kitap Listesi', 'İşlemde', '', false],
        ['346', '346-Fen Bilimleri-06', 'Fen Bilimleri', '6. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Ayşe Seyrek'], 'Kitap Listesi', 'İşlemde', '', false],
        ['271', '271-Fen Bilimleri-06', 'Fen Bilimleri', '6. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Cem Öcal'], 'Kitap Listesi', 'İşlemde', '', false],
        ['273', '273-Fen Bilimleri-06', 'Fen Bilimleri', '6. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Ömer Sinav'], 'Kitap Listesi', 'İşlemde', '', false],
        ['283', '283-Türkçe-06', 'Türkçe', '6. Sınıf', 'Ortaokul', 'Ankakuşu', '2026-11', ['Recep Çınar', 'İlyas Uslu'], 'Kitap Listesi', 'İşlemde', '', false],
        ['277', '277-Matematik-06', 'Matematik', '6. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Aysun Eseroğlu'], 'Kitap Listesi', 'İşlemde', '', false],
        ['15', '15-Din Kültürü-07', 'Din Kültürü', '7. Sınıf', 'Ortaokul', 'Tutku', '', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', true],
        ['378', '378-Din Kültürü-06', 'Din Kültürü', '6. Sınıf', 'Ortaokul', 'İpekyolu', '2025-11', ['Selahattin Çamyar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['376', '376-Din Kültürü-06', 'Din Kültürü', '6. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', false],
        ['278', '278-Sosyal Bilgiler-05', 'Sosyal Bilgiler', '5. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Hakan Işık'], 'Kitap Listesi', 'İşlemde', '', false],
        ['329', '329-Din Kültürü-05', 'Din Kültürü', '5. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['268', '268-Din Kültürü-05', 'Din Kültürü', '5. Sınıf', 'Ortaokul', 'Ankakuşu', '2025-11', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', false],
        ['267', '267-Din Kültürü-05', 'Din Kültürü', '5. Sınıf', 'Ortaokul', 'İpekyolu', '', ['Selahattin Çamyar'], 'Kitap Listesi', 'İşlemde', '', true],
        ['266', '266-Din Kültürü-05', 'Din Kültürü', '5. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['269', '269-Fen Bilimleri-05', 'Fen Bilimleri', '5. Sınıf', 'Ortaokul', 'Dikey', '2025-11', ['Ayşe Türkoğlu', 'Sümeyye Türker', 'Tuğba Bozkaya', 'Zühre Üçüncü'], 'Kitap Listesi', 'İşlemde', '', false],
        ['284', '284-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Murat Ertan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['276', '276-Matematik-05', 'Matematik', '5. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Meryem Avcı', 'Züleyha Ertan Kantos'], 'Kitap Listesi', 'İşlemde', '', false],
        ['56', '56-Trafik Güvenliği-04', 'Trafik Güvenliği', '4. Sınıf', 'İlkokul', 'Ankakuşu', '', ['Berna Akbunar', 'Mine Yüzbaş'], 'Kitap Listesi', 'İşlemde', '', true],
        ['180', '180-Din Kültürü-04', 'Din Kültürü', '4. Sınıf', 'İlkokul', 'Tutku', '', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', true],
        ['127', '127-Din Kültürü-04', 'Din Kültürü', '4. Sınıf', 'İlkokul', 'Dikey', '', ['Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', true],
        ['01', '01-Din Kültürü-04', 'Din Kültürü', '4. Sınıf', 'İlkokul', 'İpekyolu', '', ['Safiye Özdemir'], 'Kitap Listesi', 'İşlemde', '', true],
        ['83', '83-Türkçe-04', 'Türkçe', '4. Sınıf', 'İlkokul', 'İpekyolu', '2025-11', ['Ayten Erdoğan', 'Engin Ekici'], 'Kitap Listesi', 'İşlemde', '', false],
        ['340', '340-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Samet Tunalı'], 'Kitap Listesi', 'İşlemde', '', false],
        ['375', '375-Türkçe-02', 'Türkçe', '2. Sınıf', 'İlkokul', 'Dikey', '2026-11', ['Mine Yüzbaş (Sabri)'], 'Kitap Listesi', 'İşlemde', '', false],
        ['357', '357-Türkçe-02', 'Türkçe', '2. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Çiğdem Kılıçarslan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['343', '343-Matematik-02', 'Matematik', '2. Sınıf', 'İlkokul', 'İpekyolu', '2025-11', ['Yeliz Çelen'], 'Kitap Listesi', 'İşlemde', '', false],
        ['342', '342-Matematik-02', 'Matematik', '2. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Büşra Usluoğlu'], 'Kitap Listesi', 'İşlemde', '', false],
        ['359', '359-Matematik-02', 'Matematik', '2. Sınıf', 'İlkokul', 'Dikey', '2026-11', ['Çiğdem Kılıçarslan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['252', '252-Hayat Bilgisi-01', 'Hayat Bilgisi', '1. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Berna Akbunar (Öznur Tunalı)'], 'Kitap Listesi', 'İşlemde', '', false],
        ['264', '264-Türkçe (1.Grup)-01', 'Türkçe (1.Grup)', '1. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Berna Akbunar (Sabri)'], 'Kitap Listesi', 'İşlemde', '', false],
        ['263', '263-Türkçe (2.Grup)-01', 'Türkçe (2.Grup)', '1. Sınıf', 'İlkokul', 'Dikey', '2026-11', ['Mine Yüzbaş (Sabri)'], 'Kitap Listesi', 'İşlemde', '', false],
        ['314', '314-Türkçe-01', 'Türkçe', '1. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Duygu Başerdem'], 'Kitap Listesi', 'İşlemde', '', false],
        ['259', '259-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Meryem Avcı', 'Züleyha Ertan Kantos'], 'Kitap Listesi', 'İşlemde', '', false],
        ['257', '257-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Elif Çeltik'], 'Kitap Listesi', 'İşlemde', '', false],
        ['258', '258-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Mine Yüzbaş'], 'Kitap Listesi', 'İşlemde', '', false],
        ['255', '255-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Ankakuşu', '2025-03', ['Berna Akbunar'], 'Kitap Listesi', 'İşlemde', '', true],
        ['422', '422-Fen Bilimleri-07', 'Fen Bilimleri', '7. Sınıf', 'Ortaokul', 'İpekyolu', '2026-11', ['Tuğba Bozkaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['421', '421-Din Kültürü-07', 'Din Kültürü', '7. Sınıf', 'Ortaokul', 'Ankakuşu', '2026-11', ['Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['420', '420-Din Kültürü-07', 'Din Kültürü', '7. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', false],
        ['419', '419-Din Kültürü-07', 'Din Kültürü', '7. Sınıf', 'Ortaokul', 'İpekyolu', '2026-11', ['Selahattin Çamyar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['418', '418-Matematik-03', 'Matematik', '3. Sınıf', 'İlkokul', '', '2026-11', ['Berna Akbunar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['417', '417-Fen Bilimleri-03', 'Fen Bilimleri', '3. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Sümeyye Türker', 'Zühre Üçüncü'], 'Kitap Listesi', 'İşlemde', '', false],
        ['416', '416-Fen Bilimleri-03', 'Fen Bilimleri', '3. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Tuğba Bozkaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['415', '415-Kimya-11', 'Kimya', '11. Sınıf', 'Lise', 'Dikey', '2026-11', ['Uğur Bozkaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['414', '414-Din Kültürü-11', 'Din Kültürü', '11. Sınıf', 'Lise', 'Dikey', '2026-11', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['413', '413-Fen Bilimleri-07', 'Fen Bilimleri', '7. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Ayşe Seyrek'], 'Kitap Listesi', 'İşlemde', '', false],
        ['408', '408-Sosyal Bilgiler-06', 'Sosyal Bilgiler', '6. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Hakan Işık', 'İsmail Yıldız'], 'Kitap Listesi', 'İşlemde', '', false],
        ['407', '407-Matematik-11', 'Matematik', '11. Sınıf', 'Lise', 'Tutku', '2026-11', ['Filiz Çınarbay'], 'Kitap Listesi', 'İşlemde', '', false],
        ['349', '349-Coğrafya-10', 'Coğrafya', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Bahattin', 'İhsan Yüksel'], 'Kitap Listesi', 'İşlemde', '', false],
        ['405', '405-Tarih-09', 'Tarih', '9. Sınıf', 'Lise', 'Tutku', '2026-11', ['Şenol Çam'], 'Kitap Listesi', 'İşlemde', '', false],
        ['404', '404-Türk Dili ve Edebiyatı-11', 'Türk Dili ve Edebiyatı', '11. Sınıf', 'Lise', 'Tutku', '2026-11', ['Resul Gündoğar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['403', '403-Türk Dili ve Edebiyatı-10', 'Türk Dili ve Edebiyatı', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Gülay Yamaner'], 'Kitap Listesi', 'İşlemde', '', false],
        ['402', '402-Türk Dili ve Edebiyatı-09', 'Türk Dili ve Edebiyatı', '9. Sınıf', 'Lise', 'Tutku', '2026-11', ['Mehmet Akif Duman'], 'Kitap Listesi', 'İşlemde', '', false],
        ['401', '401-Türk Dili ve Edebiyatı-09', 'Türk Dili ve Edebiyatı', '9. Sınıf', 'Lise', 'Tutku', '2026-11', ['Ömer Faruk Sifil'], 'Kitap Listesi', 'İşlemde', '', false],
        ['400', '400-İngilizce-09', 'İngilizce', '9. Sınıf', 'Lise', 'Tutku', '2026-11', ['Yasemin Demir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['399', '399-Matematik-05', 'Matematik', '5. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Filyas Bayutmuş'], 'Kitap Listesi', 'İşlemde', '', false],
        ['398', '398-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'Tutku', '2026-11', ['Seyhan Kübra Esmer'], 'Kitap Listesi', 'İşlemde', '', false],
        ['397', '397-İngilizce-10', 'İngilizce', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Mehmet Şener'], 'Kitap Listesi', 'İşlemde', '', false],
        ['395', '395-İngilizce-06', 'İngilizce', '6. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Sude Sözügeçen'], 'Kitap Listesi', 'İşlemde', '', false],
        ['394', '394-İngilizce-05', 'İngilizce', '5. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Hande Çetin'], 'Kitap Listesi', 'İşlemde', '', false],
        ['393', '393-İngilizce-03', 'İngilizce', '3. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Mehmet Şener'], 'Kitap Listesi', 'İşlemde', '', false],
        ['392', '392-Matematik-03', 'Matematik', '3. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Bilge Şirin Uzunlar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['391', '391-İngilizce-02', 'İngilizce', '2. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Su Ertürk'], 'Kitap Listesi', 'İşlemde', '', false],
        ['390', '390-Hayat Bilgisi-03', 'Hayat Bilgisi', '3. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Gürhan Dikmen'], 'Kitap Listesi', 'İşlemde', '', false],
        ['387', '387-Hayat Bilgisi-03', 'Hayat Bilgisi', '3. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Esra Kül', 'Özlem Öcal'], 'Kitap Listesi', 'İşlemde', '', false],
        ['302', '302-Kimya-10', 'Kimya', '10. Sınıf', 'Lise', 'Dikey', '2026-11', ['Filiz Sarıten Aydoğan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['353', '353-Kimya-10', 'Kimya', '10. Sınıf', 'Lise', 'Dikey', '2025-11', ['Uğur Bozkaya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['299', '299-Kimya-09', 'Kimya', '9. Sınıf', 'Lise', 'Ankakuşu', '2026-11', ['Meltem Yıldız'], 'Kitap Listesi', 'İşlemde', '', false],
        ['301', '301-Kimya-09', 'Kimya', '9. Sınıf', 'Lise', 'Dikey', '2026-11', ['Filiz Sarıten Aydoğan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['104', '104-Matematik-11', 'Matematik', '11. Sınıf', 'Lise', 'Dikey', '', ['Celalettin Keskin'], 'Kitap Listesi', 'İşlemde', '', true],
        ['380', '380-Peygamber Efendimizin Hayatı-06', 'Peygamber Efendimizin Hayatı', '6. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['350', '350-Fizik-10', 'Fizik', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Fatma Dilek Esen'], 'Kitap Listesi', 'İşlemde', '', false],
        ['351', '351-Fizik-10', 'Fizik', '10. Sınıf', 'Lise', 'Ankakuşu', '2026-11', ['Muhammed Çoruh'], 'Kitap Listesi', 'İşlemde', '', false],
        ['352', '352-Fizik-10', 'Fizik', '10. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Abdullah Urhan', 'Tuncay Sargın'], 'Kitap Listesi', 'İşlemde', '', false],
        ['296', '296-Fizik-10', 'Fizik', '10. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Murat Boncuk'], 'Kitap Listesi', 'İşlemde', '', false],
        ['298', '298-Fizik-09', 'Fizik', '9. Sınıf', 'Lise', 'Dikey', '2026-11', ['Musa Özcan', 'Mustafa Gür'], 'Kitap Listesi', 'İşlemde', '', false],
        ['293', '293-Fizik-09', 'Fizik', '9. Sınıf', 'Lise', 'Ankakuşu', '2025-11', ['Muhammed Çoruh'], 'Kitap Listesi', 'İşlemde', '', false],
        ['40', '40-Biyoloji-12', 'Biyoloji', '12. Sınıf', 'Lise', 'İpekyolu', '', ['Halime Cengiz'], 'Kitap Listesi', 'İşlemde', '', true],
        ['365', '365-Türk Dili ve Edebiyatı-10', 'Türk Dili ve Edebiyatı', '10. Sınıf', 'Lise', '', '2026-11', ['Sevgi Arslan'], 'Kitap Listesi', 'İşlemde', '', false],
        ['334', '334-Türk Dili ve Edebiyatı-10', 'Türk Dili ve Edebiyatı', '10. Sınıf', 'Lise', 'Baydaş', '2025-11', ['Hayrettin Yiğit'], 'Kitap Listesi', 'İşlemde', '', false],
        ['311', '311-Türk Dili ve Edebiyatı-10', 'Türk Dili ve Edebiyatı', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Ömer Faruk Sifil'], 'Kitap Listesi', 'İşlemde', '', false],
        ['308', '308-Matematik-10', 'Matematik', '10. Sınıf', 'Lise', 'Dikey', '2026-11', ['Soner Oruçlar'], 'Kitap Listesi', 'İşlemde', '', false],
        ['309', '309-Matematik-10', 'Matematik', '10. Sınıf', 'Lise', 'Ankakuşu', '2026-11', ['Barış Burçin Demir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['305', '305-Matematik-10', 'Matematik', '10. Sınıf', 'Lise', 'Dikey', '2026-11', ['Celalettin Keskin'], 'Kitap Listesi', 'İşlemde', '', false],
        ['330', '330-Peygamberimizin Hayatı-05', 'Peygamberimizin Hayatı', '5. Sınıf', 'Ortaokul', 'Tutku', '', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', true],
        ['53', '53-Biyoloji-11', 'Biyoloji', '11. Sınıf', '', 'Tutku', '', ['Ender Ünver', 'Zafer Arslan'], 'Kitap Listesi', 'İşlemde', '', true],
        ['336', '336-Biyoloji-10', 'Biyoloji', '10. Sınıf', 'Lise', 'Baydaş', '2025-11', ['Salim İlker Filiz'], 'Kitap Listesi', 'İşlemde', '', false],
        ['288', '288-Biyoloji-09', 'Biyoloji', '9. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Cenk Durmuşkahya'], 'Kitap Listesi', 'İşlemde', '', false],
        ['285', '285-Biyoloji-09', 'Biyoloji', '9. Sınıf', 'Lise', 'Tutku', '2026-11', ['Halime Cengiz'], 'Kitap Listesi', 'İşlemde', '', false],
        ['313', '313-Türk Dili ve Edebiyatı-09', 'Türk Dili ve Edebiyatı', '9. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Hayrettin Yiğit'], 'Kitap Listesi', 'İşlemde', '', false],
        ['304', '304-Matematik-09', 'Matematik', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Mehmet Hanefi Altun'], 'Kitap Listesi', 'İşlemde', '', false],
        ['364', '364-Matematik-09', 'Matematik', '9. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Yeliz Çelen'], 'Kitap Listesi', 'İşlemde', '', false],
        ['307', '307-Matematik-09', 'Matematik', '9. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Salih Yıldız'], 'Kitap Listesi', 'İşlemde', '', false],
        ['306', '306-Matematik-09', 'Matematik', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Ayşegül Arzu Bayram'], 'Kitap Listesi', 'İşlemde', '', false],
        ['176', '176-Kuran-ı Kerim-07', 'Kuran-ı Kerim', '7. Sınıf', 'Ortaokul', 'Dikey', '', ['Bekir Pınarbaşı'], 'Kitap Listesi', 'İşlemde', '', true],
        ['80', '80-Matematik-08', 'Matematik', '8. Sınıf', 'Ortaokul', 'Dikey', '', ['Celalettin Keskin'], 'Kitap Listesi', 'İşlemde', '', true],
        ['190', '190-İngilizce-07', 'İngilizce', '7. Sınıf', 'Ortaokul', 'Ankakuşu', '', ['Esra Kandilci'], 'Kitap Listesi', 'İşlemde', '', true],
        ['381', '381-Din Kültürü-10', 'Din Kültürü', '10. Sınıf', 'Lise', 'Dikey', '2025-11', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', false],
        ['292', '292-Din Kültürü-09', 'Din Kültürü', '9. Sınıf', 'Lise', 'Dikey', '', ['Bekir Pınarbaşı', 'Fikri Özdemir'], 'Kitap Listesi', 'İşlemde', '', true],
        ['429', '429-Fizik-11', 'Fizik', '11. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Abdullah Urhan', 'Tuncay Sargın'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['412', '412-Fen Bilimleri-03', 'Fen Bilimleri', '3. Sınıf', 'İlkokul', 'Dikey', '2026-11', ['Ayşe Seyrek'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['388', '388-Hayat Bilgisi-03', 'Hayat Bilgisi', '3. Sınıf', 'İlkokul', 'Tutku', '2026-11', ['Samet Tunalı'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['430', '430-Kimya-11', 'Kimya', '11. Sınıf', 'Lise', 'İpekyolu', '2026-11', ['Emel Filiz'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['363', '363-Fizik-10', 'Fizik', '10. Sınıf', 'Lise', '', '2026-11', ['İlknur ÖZkan'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['272', '272-Fen Bilimleri-05', 'Fen Bilimleri', '5. Sınıf', 'Ortaokul', 'İpekyolu', '2026-11', ['Murat Elden', 'Ramazan Kaya'], 'Ön İnceleme', 'İşlemde', '', false],
        ['409', '409-Kimya-11', 'Kimya', '11. Sınıf', 'Lise', '', '2026-11', ['Barış Demirdağ'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['406', '406-Coğrafya-09', 'Coğrafya', '9. Sınıf', 'Lise', 'Dikey', '2026-11', ['Mustafa Karagöz'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['361', '361-Biyoloji-10', 'Biyoloji', '10. Sınıf', 'Lise', 'Dikey', '2026-11', ['Ender Ünver', 'Halime Cengiz', 'Zafer Arslan'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['385', '385-Türkçe-06', 'Türkçe', '6. Sınıf', 'Ortaokul', 'İpekyolu', '2026-11', ['Gökmen Kahraman'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['282', '282-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Deniz Yavuz'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['411', '411-Biyoloji-09', 'Biyoloji', '9. Sınıf', 'Lise', '', '2026-11', ['Ender Ünver', 'Zafer Arslan'], 'Ön İnceleme', 'İşlemde', 'Murat Şimşek', false],
        ['291', '291-Din Kültürü-09', 'Din Kültürü', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Fikri Özdemir', 'Selahattin Çamyar'], 'Türkçe Okuma', 'İşlemde', '', false],
        ['315', '315-Hayat Bilgisi-01', 'Hayat Bilgisi', '1. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Ayşe Türkoğlu', 'Naime Yaz'], 'Türkçe Okuma', 'Onaylanmış', '', false],
        ['262', '262-Türkçe-01', 'Türkçe', '1. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Çiğdem Kılıçarslan'], 'Türkçe Okuma', 'Onaylanmış', '', false],
        ['254', '254-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Dikey', '2025-11', ['Çiğdem Kılıçarslan'], 'Türkçe Okuma', 'Onaylanmış', '', false],
        ['290', '290-Din Kültürü-09', 'Din Kültürü', '9. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Fikri Özdemir', 'Selahattin Çamyar'], 'Türkçe Okuma', 'İşlemde', '', false],
        ['251', '251-Hayat Bilgisi-01', 'Hayat Bilgisi', '1. Sınıf', 'İlkokul', 'Dikey', '2025-11', ['Çiğdem Kılıçarslan'], 'Türkçe Okuma', 'Onaylanmış', '', false],
        ['377', '377-Din Kültürü-06', 'Din Kültürü', '6. Sınıf', 'Ortaokul', 'Tutku', '2025-11', ['Fikri Özdemir'], 'Türkçe Okuma', 'İşlemde', '', false],
        ['297', '297-Fizik-09', 'Fizik', '9. Sınıf', 'Lise', 'Tutku', '2025-11', ['Fatma Dilek Esen'], 'Türkçe Okuma', 'Onaylanmış', '', false],
        ['358', '358-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', 'Dikey', '2026-11', ['Çiğdem Kılıçarslan'], 'Türkçe Okuma', 'İşlemde', '', false],
        ['339', '339-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Zülay Karabey'], 'Dijital Üretim Süreci', 'İşlemde', 'Rümeysa Çiftçi', false],
        ['312', '312-Türk Dili ve Edebiyatı-09', 'Türk Dili ve Edebiyatı', '9. Sınıf', 'Lise', 'Ankakuşu', '2026-11', ['Recep Çınar'], 'Dijital Üretim Süreci', 'İşlemde', 'Kübra Doğan', false],
        ['396', '396-İngilizce-09', 'İngilizce', '9. Sınıf', 'Lise', 'Dikey', '2026-11', ['Necla Tuğba Yüksel'], 'Dijital Üretim Süreci', 'İşlemde', 'Cemile Yavuz', false],
        ['294', '294-Fizik-09', 'Fizik', '9. Sınıf', 'Lise', 'İpekyolu', '2025-11', ['Abdullah Urhan', 'Tuncay Sargın'], 'Ön Kontrol (V1)', 'İşlemde', 'Furkan Çelebi', false],
        ['366', '366-Türkçe-02', 'Türkçe', '2. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Öznur Doğan'], 'Scorm (V2) Aşaması', 'İşlemde', 'Kübra Doğan', false],
        ['386', '386-İngilizce-02', 'İngilizce', '2. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Esengül Koçak', 'Esra Kandilci'], 'Scorm (V2) Aşaması', 'İşlemde', 'Cemile Yavuz', false],
        ['333', '333-Matematik-10', 'Matematik', '10. Sınıf', 'Lise', 'Baydaş', '2025-11', ['Cüneyt Akçakaya'], 'Scorm (V2) Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['279', '279-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'İpekyolu', '2025-11', ['Engin Ekici', 'Zülay Karabey'], 'Scorm (V2) Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['410', '410-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', '', '2026-11', ['Ayşe Türkoğlu', 'Naime Yaz'], 'Scorm (V2) Aşaması', 'İşlemde', 'Kübra Doğan', false],
        ['355', '355-Tarih-10', 'Tarih', '10. Sınıf', 'Lise', 'Tutku', '2026-11', ['Hakan Işık'], 'Scorm (V2) Aşaması', 'İşlemde', 'Fatma Tekdemir', false],
        ['250', '250-Hayat Bilgisi-01', 'Hayat Bilgisi', '1. Sınıf', 'İlkokul', 'İpekyolu', '2025-11', ['Mine Yüzbaş (Zülay Karabey)'], 'Scorm (V2) Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['389', '389-Hayat Bilgisi-03', 'Hayat Bilgisi', '3. Sınıf', 'İlkokul', 'İpekyolu', '2026-11', ['Berna Akbunar'], 'Scorm (V2) Aşaması', 'İşlemde', 'Kübra Doğan', false],
        ['256', '256-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'Tutku', '2025-11', ['Büşra Usluoğlu'], 'Scorm (V2) Aşaması', 'Onaylanmış', 'Furkan Çelebi', false],
        ['274', '274-Fen Bilimleri-05', 'Fen Bilimleri', '5. Sınıf', 'Ortaokul', 'Dikey', '2026-11', ['Ender Ünver', 'Zafer Arslan'], 'Scorm (V2) Aşaması', 'Onaylanmış', 'Furkan Çelebi', false],
        ['280', '280-Türkçe-05', 'Türkçe', '5. Sınıf', 'Ortaokul', 'İpekyolu', '2026-11', ['Seda Seyhan', 'Serdal Sevindi'], 'Scorm (V2) Aşaması', 'Onaylanmış', 'Furkan Çelebi', false],
        ['345', '345-Matematik-02', 'Matematik', '2. Sınıf', 'İlkokul', 'Ankakuşu', '2026-11', ['Mine Yüzbaş'], 'Tashih Aşaması', 'İşlemde', 'Rümeysa Çiftçi', false],
        ['260', '260-Matematik-01', 'Matematik', '1. Sınıf', 'İlkokul', 'İpekyolu', '2025-11', ['Öznur Doğan'], 'Son Kontrol Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['265', '265-Türkçe-01', 'Türkçe', '1. Sınıf', 'İlkokul', 'Baydaş', '2026-11', ['Öznur Doğan'], 'Son Kontrol Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['356', '356-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', 'Baydaş', '2026-11', ['Öznur Doğan'], 'Son Kontrol Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['335', '335-Matematik-02', 'Matematik', '2. Sınıf', 'İlkokul', 'Baydaş', '2026-11', ['Öznur Doğan'], 'Son Kontrol Aşaması', 'İşlemde', 'Furkan Çelebi', false],
        ['337', '337-Kimya-10', 'Kimya', '10. Sınıf', 'Lise', 'Baydaş', '2025-11', ['Emel Filiz'], 'Son Kontrol Aşaması', 'İşlemde', '', false],
        ['253', '253-Hayat Bilgisi-01', 'Hayat Bilgisi', '1. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Öznur Doğan'], 'Son Kontrol Aşaması', 'Onaylanmış', 'Furkan Çelebi', false],
        ['338', '338-Hayat Bilgisi-02', 'Hayat Bilgisi', '2. Sınıf', 'İlkokul', 'Ankakuşu', '2025-11', ['Berna Akbunar', 'Mine Yüzbaş'], 'Son Kontrol Aşaması', 'Onaylanmış', 'Furkan Çelebi', false],
    ];
}

function eit_get_categories() {
    return [
        'siniflar' => [
            '1. Sınıf' => 17,
            '2. Sınıf' => 16,
            '3. Sınıf' => 10,
            '4. Sınıf' => 5,
            '5. Sınıf' => 18,
            '6. Sınıf' => 13,
            '7. Sınıf' => 10,
            '8. Sınıf' => 4,
            '9. Sınıf' => 28,
            '10. Sınıf' => 26,
            '11. Sınıf' => 12,
            '12. Sınıf' => 3
        ],
        'dersler' => [
            'Türkçe' => 15,
            'Matematik' => 30,
            'Biyoloji' => 10,
            'Tarih' => 4,
            'Peygamberimizin Hayatı' => 2,
            'Fen Bilimleri' => 14,
            'Kimya' => 11,
            'Fizik' => 12,
            'İngilizce' => 11,
            'Din Kültürü' => 19,
            'Sosyal Bilgiler' => 2,
            'Trafik Güvenliği' => 1,
            'Hayat Bilgisi' => 15,
            'Türkçe (1.Grup)' => 1,
            'Türkçe (2.Grup)' => 1,
            'Coğrafya' => 2,
            'Türk Dili ve Edebiyatı' => 9,
            'Peygamber Efendimizin Hayatı' => 1,
            'Kuran-ı Kerim' => 1
        ],
        'yazarlar' => [
            'Bekir Pınarbaşı' => 13,
            'Fikri Özdemir' => 13,
            'Ender Ünver' => 6,
            'Zafer Arslan' => 6,
            'Çiğdem Kılıçarslan' => 6,
            'Öznur Doğan' => 6,
            'Sümeyye Türker' => 5,
            'Zühre Üçüncü' => 5,
            'Tuğba Bozkaya' => 5,
            'Selahattin Çamyar' => 5,
            'Berna Akbunar' => 5,
            'Halime Cengiz' => 4,
            'Celalettin Keskin' => 4,
            'Hakan Işık' => 4,
            'Ayşe Seyrek' => 4,
            'Esra Kandilci' => 4,
            'Mine Yüzbaş' => 4,
            'Barış Demirdağ' => 3,
            'Uğur Bozkaya' => 3,
            'Muhammed Çoruh' => 3,
            'Ayşe Türkoğlu' => 3,
            'Abdullah Urhan' => 3,
            'Tuncay Sargın' => 3,
            'Cüneyt Akçakaya' => 2,
            'Salim İlker Filiz' => 2,
            'Salih Yıldız' => 2,
            'İlknur ÖZkan' => 2,
            'Necla Tuğba Yüksel' => 2,
            'Recep Çınar' => 2,
            'Meryem Avcı' => 2,
            'Züleyha Ertan Kantos' => 2,
            'Engin Ekici' => 2,
            'Samet Tunalı' => 2,
            'Mine Yüzbaş (Sabri)' => 2,
            'Yeliz Çelen' => 2,
            'Büşra Usluoğlu' => 2,
            'Ömer Faruk Sifil' => 2,
            'Mehmet Şener' => 2,
            'Filiz Sarıten Aydoğan' => 2,
            'Fatma Dilek Esen' => 2,
            'Hayrettin Yiğit' => 2,
            'Emel Filiz' => 2,
            'Naime Yaz' => 2,
            'Zülay Karabey' => 2,
            'Arzu Demirel' => 1,
            'Vicdan Özbay' => 1,
            'Murat Usta' => 1,
            'Cem Öcal' => 1,
            'Ömer Sinav' => 1,
            'İlyas Uslu' => 1,
            'Aysun Eseroğlu' => 1,
            'Murat Ertan' => 1,
            'Safiye Özdemir' => 1,
            'Ayten Erdoğan' => 1,
            'Berna Akbunar (Öznur Tunalı)' => 1,
            'Berna Akbunar (Sabri)' => 1,
            'Duygu Başerdem' => 1,
            'Elif Çeltik' => 1,
            'İsmail Yıldız' => 1,
            'Filiz Çınarbay' => 1,
            'Bahattin' => 1,
            'İhsan Yüksel' => 1,
            'Şenol Çam' => 1,
            'Resul Gündoğar' => 1,
            'Gülay Yamaner' => 1,
            'Mehmet Akif Duman' => 1,
            'Yasemin Demir' => 1,
            'Filyas Bayutmuş' => 1,
            'Seyhan Kübra Esmer' => 1,
            'Sude Sözügeçen' => 1,
            'Hande Çetin' => 1,
            'Bilge Şirin Uzunlar' => 1,
            'Su Ertürk' => 1,
            'Gürhan Dikmen' => 1,
            'Esra Kül' => 1,
            'Özlem Öcal' => 1,
            'Meltem Yıldız' => 1,
            'Murat Boncuk' => 1,
            'Musa Özcan' => 1,
            'Mustafa Gür' => 1,
            'Sevgi Arslan' => 1,
            'Soner Oruçlar' => 1,
            'Barış Burçin Demir' => 1,
            'Cenk Durmuşkahya' => 1,
            'Mehmet Hanefi Altun' => 1,
            'Ayşegül Arzu Bayram' => 1,
            'Murat Elden' => 1,
            'Ramazan Kaya' => 1,
            'Mustafa Karagöz' => 1,
            'Gökmen Kahraman' => 1,
            'Deniz Yavuz' => 1,
            'Esengül Koçak' => 1,
            'Mine Yüzbaş (Zülay Karabey)' => 1,
            'Seda Seyhan' => 1,
            'Serdal Sevindi' => 1
        ],
        'yayinevleri' => [
            'Tutku' => 51,
            'İpekyolu' => 35,
            'Belirtilmemis' => 7,
            'Dikey' => 43,
            'Ankakuşu' => 19,
            'Baydaş' => 7
        ],
        'okullar' => [
            'Ortaokul' => 45,
            'Lise' => 68,
            'İlkokul' => 48,
            'Belirtilmemis' => 1
        ],
        'asamalar' => [
            'Kitap Listesi' => 118,
            'Ön İnceleme' => 12,
            'Türkçe Okuma' => 9,
            'Dijital Üretim Süreci' => 3,
            'Ön Kontrol (V1)' => 1,
            'Scorm (V2) Aşaması' => 11,
            'Tashih Aşaması' => 1,
            'Son Kontrol Aşaması' => 7
        ],
        'donemler' => [
            '2025-03' => 1,
            '2025-11' => 59,
            '2026-11' => 88,
            'Belirtilmemiş' => 14
        ],
        'atananlar' => [
            'Furkan Çelebi' => 13,
            'Murat Şimşek' => 12,
            'Kübra Doğan' => 4,
            'Rümeysa Çiftçi' => 2,
            'Cemile Yavuz' => 2,
            'Fatma Tekdemir' => 1,
            'Atanmamış' => 128
        ],
        'durumlar' => [
            'İşlemde' => 155,
            'Onaylanmış' => 7,
            'Askıda' => 0,
            'Pasif' => 0
        ],
    ];
}
